# frozen_string_literal: true

source 'https://rubygems.org'

gem 'awspec'
gem 'confidante'
gem 'git'
gem 'netaddr'
gem 'net-ssh'
gem 'rake'
gem 'rake_circle_ci', '>= 0.13.0'
gem 'rake_git', '>= 0.2.0'
gem 'rake_git_crypt', '>= 0.2.0'
gem 'rake_github', '>= 0.13.0'
gem 'rake_gpg', '>= 0.20.0'
gem 'rake_ssh', '>= 0.10.0'
gem 'rake_terraform', '>= 1.24.0'
gem 'rspec'
gem 'rspec-terraform'
gem 'rubocop', '>= 1.46.0'
gem 'rubocop-rake'
gem 'rubocop-rspec', '>= 2.19.0'
gem 'rubyzip'
gem 'semantic'
