---
source_directory: "spec/infra/harness"
state_file: "%{hiera('project_directory')}/state/harness.tfstate"
vars:
  region: "%{hiera('region')}"

  component: "%{hiera('component')}"
  deployment_identifier: "%{hiera('deployment_identifier')}"

  vpc_cidr: "%{hiera('vpc_cidr')}"
  availability_zones: "%{hiera('availability_zones')}"

  public_subnets_offset: "%{hiera('public_subnets_offset')}"
  private_subnets_offset: "%{hiera('private_subnets_offset')}"

  dependencies: "%{hiera('dependencies')}"

  private_zone_vpc_id: "%{hiera('private_zone_vpc_id')}"

  include_route53_zone_association: "%{hiera('include_route53_zone_association')}"
  include_nat_gateways: "%{hiera('include_nat_gateways')}"
